[package]
name = "rust_websocket_client"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.2.2"
tungstenite = { version = "0.26.1", features = ["rustls-tls-native-roots"] }
serde_json = "1.0.138"
native-tls = "0.2.13"
rustls = "0.23"